### ISSUE TITLE
How to validate the each predictor's row level SHAP values with predicted probability? 

### ISSUE THREAD

**Issue by sandeshregmi** [cran/iml#1]
I built a classification model using caret's xgbDART method. Then used IML package for SHAP vanalysis. My understanding is that "phi" variable in "result" object is log odds and we can convert them to probability scores. If we add those probability scores, we should get the model's predicted probability score!
Is this how we validate the SHAP results?
Any direction would be appreciated.
Thank you
sandesh

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the DESCRIPTION file. Thanks!
